# Generated by Django 3.2.12 on 2023-04-15 22:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('type', models.CharField(choices=[('PASS', 'Легковой'), ('TRUCK', 'Грузовой'), ('BUS', 'Автобус')], max_length=10, verbose_name='Тип авто')),
                ('body_type', models.CharField(help_text='Тип кузова', max_length=70, null=True, verbose_name='Тип кузова')),
                ('fuel_tank', models.DecimalField(decimal_places=2, default=30, help_text='Объем топливного бака', max_digits=5, null=True, verbose_name='Объем бака')),
                ('seats_number', models.IntegerField(help_text='Количество пассажиров', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)], verbose_name='Вместимость')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название предприятия', max_length=255, unique=True, verbose_name='Название предприятия')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('country', models.CharField(max_length=255, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Предприятие',
                'verbose_name_plural': 'Предприятия',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('release_year', models.IntegerField(verbose_name='Год выпуска')),
                ('mileage', models.IntegerField(verbose_name='Пробег')),
                ('number', models.CharField(max_length=20, verbose_name='Гос. номер')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='vehicle.brand', verbose_name='Бренд')),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='vehicle.enterprise', verbose_name='Предприятие')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=80, verbose_name='Фамилия')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(80)], verbose_name='Возраст')),
                ('salary', models.IntegerField(verbose_name='Зарплата')),
                ('is_active', models.BooleanField(default=False)),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='vehicle.enterprise', verbose_name='Предприятие')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='vehicle.vehicle')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
            },
        ),
    ]
