# Generated by Django 3.2.12 on 2023-04-08 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='gas_tank_volume',
            field=models.IntegerField(default=30, verbose_name='Объем бака'),
        ),
        migrations.AddField(
            model_name='brand',
            name='seats_number',
            field=models.IntegerField(default=4, verbose_name='Количество мест'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='vehicle.brand', verbose_name='Бренд'),
        ),
    ]
