# Generated by Django 4.2.3 on 2023-07-21 15:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('type', models.CharField(choices=[('PASS', 'Легковой'), ('TRUCK', 'Грузовой'), ('BUS', 'Автобус')], max_length=10, verbose_name='Тип авто')),
                ('body_type', models.CharField(help_text='Тип кузова', max_length=70, null=True, verbose_name='Тип кузова')),
                ('fuel_tank', models.DecimalField(decimal_places=2, default=30, help_text='Объем топливного бака', max_digits=5, null=True, verbose_name='Объем бака')),
                ('seats_number', models.IntegerField(help_text='Количество пассажиров', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)], verbose_name='Вместимость')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='vehicle.brand', verbose_name='Бренд'),
        ),
    ]
